import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Navbar from "../components/navbar/Navbar";
import MainImg from "../public/images/header.jpg";
import Img2 from "../public/images/image-6.jpg";
import { BiChevronRight } from "react-icons/bi";
import ReactPlayer from "react-player";
import Footer from "../components/layouts/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>FE1_Ableton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* MAIN NAV */}
      <Navbar />

      <div>
        {/* MAIN PAGE */}
        <div>
          <main>
            {/* HEADER IMG */}
            <div className="mx-28 mb-28">
              <Image src={MainImg} alt="Pexels Giovanni Garnica" />
            </div>

            {/* TEXT-1 */}
            <div className="mx-80 mb-28">
              <h1 className="mb-[21px] text-3xl">
                We make <span className="text-[blue]">Live</span>,{" "}
                <span className="text-[blue]">Push</span> and{" "}
                <span className="text-[blue]">Link</span> — unique software and
                hardware for music creation and performance. With these
                products, our community of users creates amazing things.
              </h1>
              <p className="text-[1.25rm]">
                Ableton was founded in 1999 and released the first version of
                Live in 2001. Our products are used by a community of dedicated
                musicians, sound designers, and artists from across the world.
              </p>
            </div>

            {/* COLLAGE-1 */}
            <div className="relative py-8vw mb-8vw">
              <div
                className="block bg-[#fbffa7] w-[58.33333vw]
            h-[58.33333vw] left-[41.66667vw] absolute top-0 z-0"
              ></div>
              <div
                className="bg-no-repeat bg-cover bg-[url('../public/images/photo-1.jpg')]
            bg-50% w-[41.66667vw] h-[41.66667vw] ml-8vw inline-block z-[1]
            relative align-middle"
              ></div>
              <div
                className="bg-no-repeat bg-cover bg-[url('../public/images/photo-2.jpeg')]
            bg-50% w-[33.33333vw] h-[25vw] ml-8vw inline-block z-[1] relative
            align-middle"
              ></div>
            </div>

            {/* TEXT-2 */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <div className="m-bodyText">
                <h1 className="mb-[21px] text-3xl">
                  Making music isn’t easy. It takes time, effort, and learning.
                  But when you’re in the flow, it’s incredibly rewarding.
                </h1>
                <p className="text-[1.25rm]">
                  We feel the same way about making Ableton products. The
                  driving force behind Ableton is our passion for what we make,
                  and the people we make it for.
                </p>
              </div>
            </div>

            {/* MEDIA */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <a
                href="https://www.youtube.com/watch?v=9SbnhgjeyXA"
                className="block relative w-full cursor-pointer pb-[56.25%] z-40"
              ></a>
              <p>Why Ableton - Juanpe Bolivar</p>
            </div>

            {/* TEXT-3 */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <div className="m-bodyText">
                <h1 className="mb-[21px] text-3xl">
                  We are more than 350 people from 30 different countries
                  divided between our headquarters in Berlin and our offices in
                  Los Angeles and Tokyo.
                </h1>
                <p className="text-[1.25rm]">
                  Most of us are active musicians, producers, and DJs, and many
                  of us use Live and Push every day. We come from a wide range
                  of cultural and professional backgrounds. Some of us have
                  PhDs, some are self-taught, and most of us are somewhere in
                  between. What connects us is the shared belief that each of us
                  has the skills and knowledge to contribute to something big:
                  helping to shape the future of music culture.
                </p>
              </div>
            </div>

            {/* COLLAGE-2 */}
            <div className="p-8vw relative mb-8vw border-box block">
              <div className="w-[58.33333vw] h-[75vw] left-0 absolute top-0 z-0 bg-[#B6FFC0]"></div>
              <div className="inline-block align-middle relative z-1">
                <div
                  className="bg-no-repeat bg-cover bg-[url('../public/images/photo-3.jpeg')]
            bg-50% w-[33.33333vw] h-[25vw]"
                ></div>
                <div
                  className="bg-no-repeat bg-cover bg-[url('../public/images/photo-4.jpeg')]
            bg-50% w-[33.33333vw] h-[25vw] mt-8vw"
                ></div>
              </div>
              <div
                className="bg-no-repeat bg-cover bg-[url('../public/images/photo-5.jpeg')]
            bg-50% w-[41.66667vw] h-[41.66667vw] ml-8vw inline-block z-[1]
            relative align-middle"
              ></div>
            </div>

            {/* TEXT-4 */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <div className="m-bodyText">
                <h1 className="mb-[21px] text-3xl">
                  We believe it takes focus to create truly outstanding
                  instruments. We only work on a few products and we strive to
                  make them great.
                </h1>
                <p className="text-[1.25rm]">
                  Rather than having a one-size-fits-all process, we try to give
                  our people what they need to work their magic and grow. We’ve
                  learned that achieving the best results comes from building
                  teams that are richly diverse, and thus able to explore
                  problems from a wider set of perspectives. We don’t always
                  agree with each other, but opinion and debate are valued and
                  openly encouraged.
                </p>
              </div>
            </div>

            {/* IMG-2 */}
            <div className="mx-28 mb-28">
              <Image src={Img2} alt="Image-6" />
            </div>

            {/* TEXT-5 */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <div className="m-bodyText">
                <h1 className="mb-[21px] mt-0 text-3xl">
                  We’re passionate about what we do, but we’re equally
                  passionate about improving who we are.
                </h1>
                <p className="text-[1.25rm] mb-[1em]">
                  We work hard to foster an environment where people can grow
                  both personally and professionally, and we strive to create a
                  wealth of opportunities to learn from and with each other.
                </p>
                <p className="text-[1.25rm]">
                  Alongside an internal training program, employees are actively
                  supported in acquiring new knowledge and skills, and coached
                  on applying these in their daily work. In addition,
                  staff-organized development and music salons are a chance to
                  discuss new technologies, production techniques and best
                  practices.
                </p>
              </div>
            </div>

            {/* COLLAGE-3 */}
            <div className="py-8vw relative mb-8vw">
              <div
                className="w-[66.66667vw] h-[58.33333vw] left-[16.66667vw] absolute
          top-0 z-0 bg-[#D5B3FF]"
              ></div>
              <div
                className="sticky bg-no-repeat bg-cover bg-[url('../public/images/photo-7-a.jpeg')]
            bg-50% w-[33.33333vw] h-[25vw] ml-8vw left-8vw inline-block
            align-middle z-1 "
              ></div>
              <div
                className="bg-no-repeat bg-cover bg-[url('../public/images/photo-7-b.jpeg')]
            bg-50% w-[41.66667vw] h-[41.66667vw] inline-block align-middle relative
            z-1 ml-[16.66667vw]"
              ></div>
            </div>

            {/* TEXT-5 */}
            <div className="w-[50vw] mx-auto mb-[8.33338vw]">
              <div className="m-bodyText">
                <h1 className="mb-[21px] text-3xl">
                  We want our employees to love it here. Since we’re looking for
                  exceptional talent from around the world, we will do
                  everything we can to make your transition as easy as possible.
                </h1>
                <p className="text-[1.25rm]">
                  If you're joining us in Berlin, we'll help with relocation and
                  paperwork. We’ll even provide you with free German or English
                  lessons. Plus, working in Germany means you can expect
                  comprehensive health insurance for you and your family, as
                  well as generous maternity and paternity leave. Office hours
                  are flexible, but it’s not all work; we have several company
                  and team outings throughout the year as well as a variety of
                  fun, informal small-group activities.
                </p>
              </div>
            </div>

            {/* COLLAGE-4 */}
            <div>
              <div
                className="bg-no-repeat bg-cover bg-[url('../public/images/photo-8.jpeg')]
            bg-50% w-[41.66667vw] h-[41.66667vw] inline-block align-top relative
            ml-8vw"
              ></div>
              <div
                className="p-8vw w-[41.66667vw] h-[41.66667vw] inline-block
          align-top mx-0 bg-[#B1C5FF]"
              >
                <div className="table w-[100%] h-[100%]">
                  <div className="m-bodyText table-cell align-middle">
                    <h1 className="mb-0 text-3xl">
                      We’re really proud of the work we’ve done so far. But
                      there’s so much more to come. If you’d like to be a part
                      of it, please join us.
                      <a className="block mt-[1em] text-[#0000FF] flex cursor-pointer">
                        See latest jobs <BiChevronRight className="self-end" />
                      </a>
                    </h1>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>

        <Footer />
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by oui
          </a>
        </footer>
      </div>
    </>
  );
}

// import Head from "next/head";
// import Layout, { siteTitle } from "../components/layout";
// import utilStyles from "../styles/utils.module.css";
// import Link from "next/link";

// export default function Home() {
//   return (
//     <Layout home>
//       <Head>
//         <title>{siteTitle}</title>
//       </Head>
//       <section className={utilStyles.headingMd}>
//         <p>FE1_Ableton</p>
//         <p>(test ok.)</p>
//         <Link href="./posts/first-post">To First post</Link>
//       </section>
//     </Layout>
//   );
// }
